CREATE TABLE rol (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE usuario (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         VARCHAR2(120) NOT NULL UNIQUE,
  password_hash VARCHAR2(120) NOT NULL,
  nombre        VARCHAR2(80) NOT NULL,
  apellido      VARCHAR2(80) NOT NULL,
  activo        NUMBER(1) DEFAULT 1 NOT NULL,
  rol_id        NUMBER NOT NULL,
  CONSTRAINT fk_usuario_rol FOREIGN KEY (rol_id) REFERENCES rol (id)
);
CREATE INDEX idx_usuario_rol ON usuario (rol_id);

CREATE TABLE libro (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo       VARCHAR2(200) NOT NULL,
  autor        VARCHAR2(150) NOT NULL,
  isbn         VARCHAR2(20),
  editorial    VARCHAR2(100),
  precio       NUMBER(12,2) NOT NULL,
  stock        NUMBER(10) NOT NULL,
  activo       NUMBER(1) DEFAULT 1 NOT NULL,
  descripcion  VARCHAR2(500)
);
CREATE INDEX idx_libro_titulo ON libro (titulo);
CREATE INDEX idx_libro_autor ON libro (autor);

CREATE TABLE pedido (
  id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id      NUMBER NOT NULL,
  fecha_creacion  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  total           NUMBER(12,2) NOT NULL,
  estado_pago     VARCHAR2(40) NOT NULL,
  CONSTRAINT fk_pedido_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);
CREATE INDEX idx_pedido_usuario ON pedido (usuario_id);

CREATE TABLE detalle_pedido (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id    NUMBER NOT NULL,
  libro_id     NUMBER NOT NULL,
  cantidad     NUMBER(10) NOT NULL,
  subtotal     NUMBER(12,2) NOT NULL,
  CONSTRAINT fk_det_pedido FOREIGN KEY (pedido_id) REFERENCES pedido (id),
  CONSTRAINT fk_det_libro FOREIGN KEY (libro_id) REFERENCES libro (id)
);
CREATE INDEX idx_det_pedido ON detalle_pedido (pedido_id);

INSERT INTO rol (nombre) VALUES ('ADMIN');
INSERT INTO rol (nombre) VALUES ('CLIENTE');
INSERT INTO rol (nombre) VALUES ('SOPORTE');

INSERT INTO usuario (email, password_hash, nombre, apellido, activo, rol_id)
VALUES ('admin@tienda.cl', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Ana', 'Gomez', 1, 1);
INSERT INTO usuario (email, password_hash, nombre, apellido, activo, rol_id)
VALUES ('cliente1@mail.cl', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Luis', 'Perez', 1, 2);
INSERT INTO usuario (email, password_hash, nombre, apellido, activo, rol_id)
VALUES ('cliente2@mail.cl', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Maria', 'Lopez', 1, 2);

INSERT INTO libro (titulo, autor, isbn, editorial, precio, stock, activo, descripcion)
VALUES ('Cien años de soledad', 'Gabriel Garcia Marquez', '978-8437604947', 'Sudamericana', 12990, 25, 1, 'Novela fundacional del boom latinoamericano.');
INSERT INTO libro (titulo, autor, isbn, editorial, precio, stock, activo, descripcion)
VALUES ('1984', 'George Orwell', '978-8499890944', 'Debolsillo', 9990, 40, 1, 'Distopia politica clasica.');
INSERT INTO libro (titulo, autor, isbn, editorial, precio, stock, activo, descripcion)
VALUES ('El principito', 'Antoine de Saint-Exupery', '978-9569999315', 'Andres Bello', 7990, 60, 1, 'Fabula filosofica para todas las edades.');
INSERT INTO libro (titulo, autor, isbn, editorial, precio, stock, activo, descripcion)
VALUES ('Clean Code', 'Robert C. Martin', '978-0132350884', 'Prentice Hall', 45990, 12, 1, 'Buenas practicas de desarrollo de software.');
INSERT INTO libro (titulo, autor, isbn, editorial, precio, stock, activo, descripcion)
VALUES ('Patrones de diseno', 'GoF', '978-0201633612', 'Addison-Wesley', 38990, 8, 1, 'Catalogo clasico de patrones OO.');
INSERT INTO libro (titulo, autor, isbn, editorial, precio, stock, activo, descripcion)
VALUES ('Historia de Chile', 'Francisco A. Encina', '978-9560000000', 'Nascimento', 24990, 15, 1, 'Obra historica de referencia.');

INSERT INTO pedido (usuario_id, total, estado_pago) VALUES (2, 22980, 'PAGADO_SIMULADO');
INSERT INTO pedido (usuario_id, total, estado_pago) VALUES (3, 9990, 'PAGADO_SIMULADO');
INSERT INTO pedido (usuario_id, total, estado_pago) VALUES (2, 45990, 'PAGADO_SIMULADO');

INSERT INTO detalle_pedido (pedido_id, libro_id, cantidad, subtotal) VALUES (1, 1, 1, 12990);
INSERT INTO detalle_pedido (pedido_id, libro_id, cantidad, subtotal) VALUES (1, 3, 1, 9990);
INSERT INTO detalle_pedido (pedido_id, libro_id, cantidad, subtotal) VALUES (2, 2, 1, 9990);
INSERT INTO detalle_pedido (pedido_id, libro_id, cantidad, subtotal) VALUES (3, 4, 1, 45990);

COMMIT;
